baseURL = 'https://tien0246.github.io/'
languageCode = 'en-us'
title = 'tien0246 blog'
canonifyURLs = true
relativeURLs = true


[pagination]
  pagerSize = 4

[params]
  description = "Tien0246's personal blog, a place to share knowledge and experience about cybersecurity, programming, and technology."
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github-dark"

# This comment is added to trigger a new GitHub Actions workflow run


    
